name: Release
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
jobs:
    release:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repository
          uses: actions/checkout@v6
        
        - name: Create release assets
          env:
            name: ${{ github.repository }}#*/
            branch: ${{ github.ref_name }}
            tag: ${{ github.run_number }}
          run:
            git archive --format=zip --output="./bin/${name}+${branch}-build.${tag}" HEAD
        
        - name: Upload assets to GitHub
          uses: AButler/upload-release-assets@v4.0
          with:
            files: "bin/*"
            repo-token: ${{ secrets.GITHUB_TOKEN }}
            release-tag: build.${{ github.run_number }}