name: Release
on:
    workflow_dispatch:
        inputs:
            r_version:
                description: "Release version"
                required: true
            mc_version:
                description: "Minecraft version"
                required: true

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repository
          uses: actions/checkout@v6
        
        - name: Install dependencies
          run: |
            sudo apt install zip
        
        - name: Create assets
          env:
            r_version: ${{ github.event.inputs.r_version }}
            mc_version: ${{ github.event.inputs.mc_version }}
          run: |
            cd versions/${mc_version}
            zip -r ${git rev-parse --show-toplevel}/bin/${GITHUB_REPOSITORY#*/}-v${r_version}+v${mc_version}.zip *
        
        - name: Create release
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            tag: v${{ github.event.inputs.r_version }}
            minecraft: ${{ github.event.inputs.mc_version }}
          run: |
            gh release create "$tag" \
              --repo="$GITHUB_REPOSITORY" \
              --title="${tag}+${minecraft}" \
              --generate-notes
        
        - name: Upload assets to GitHub
          uses: AButler/upload-release-assets@v4.0
          with:
            files: "bin/*"
            repo-token: ${{ secrets.GITHUB_TOKEN }}
            release-tag: v${{ github.event.inputs.r_version }}