name: Release
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
jobs:
    release:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repository
          uses: actions/checkout@v6
        
        - name: Create release
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            tag: build.${{ github.run_number }}
          run: |
            gh release create "$tag" \
              --repo="$GITHUB_REPOSITORY" \
              --title="${GITHUB_REPOSITORY#*/} ${tag#v}" \
              --generate-notes
        
        - name: Create assets
          env:
            repository: ${{ github.repository }}
            branch: ${{ github.ref_name }}
            build: ${{ github.run_number }}
          run:
            zipname="${repository#*/}+${branch}-build.${build}.zip"
            echo zipname
            git archive --format=zip --output="bin/${zipname}" HEAD
        
        - name: Upload assets to GitHub
          uses: AButler/upload-release-assets@v4.0
          with:
            files: "bin/*"
            repo-token: ${{ secrets.GITHUB_TOKEN }}
            release-tag: build.${{ github.run_number }}